version: '3.8'

networks:
  elastic:
    name: jmeter_elastic
    driver: bridge

volumes:
  es-data:
    name: jmeter_es_data

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status.*green\\|status.*yellow'"]
      interval: 10s
      timeout: 10s
      retries: 3
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.3
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./log:/var/log/jmeter:ro
      - ./result:/result:ro
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    command: ["--strict.perms=false"]
    deploy:
      resources:
        limits:
          memory: 256M

  jmeter:
    image: justb4/jmeter:5.5
    user: root
    volumes:
      - ./test:/test:rw
      - ./result:/result:rw
      - ./log/jmeter:/jmeter/log:rw
    environment:
      - TZ=UTC
      - JVM_ARGS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
    working_dir: /test
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: ["/opt/apache-jmeter-5.5/bin/jmeter"]
    command: [
      "-n",
      "-t", "/test/todoist.jmx",
      "-l", "/result/result.jtl",
      "-e",
      "-o", "/result/dashboard",
      "-Jjmeter.reportgenerator.overall_granularity=1000",
      "-Jjmeter.save.saveservice.default_delimiter=,",
      "-Jjmeter.save.saveservice.print_field_names=true",
      "-Jjmeter.save.saveservice.timestamp_format=yyyy-MM-dd HH:mm:ss",
      "-Jjmeter.save.saveservice.timestamp=true",
      "-Jjmeter.save.saveservice.time=true",
      "-Jjmeter.save.saveservice.latency=true",
      "-Jjmeter.save.saveservice.label=true",
      "-Jjmeter.save.saveservice.success=true",
      "-Jjmeter.save.saveservice.response_code=true",
      "-Jjmeter.save.saveservice.response_message=true",
      "-Jjmeter.save.saveservice.thread_name=true",
      "-Jjmeter.save.saveservice.thread_counts=true",
      "-Jjmeter.save.saveservice.bytes=true",
      "-Jjmeter.save.saveservice.url=true",
      "-Jjmeter.save.saveservice.connect_time=true",
      "-Jjmeter.save.saveservice.response_data=false",
      "-Jjmeter.save.saveservice.samplerData=false",
      "-Jjmeter.save.saveservice.subresults=false",
      "-Jjmeter.save.saveservice.assertion_results_failure_message=false"
    ]
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M